services:
  file-transfer-go:
    build: .
    image: llinyin789456/file-transfer-go:latest
    container_name: file-transfer-go
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
    # 暂不需要挂载数据卷
    # volumes:
    #   - ./data:/app/data
